server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true    
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 456339345628-2kobkpho4mp5p7en3cfhn5gp5ji2ntf0.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
            
          facebook:
            client-id: 1189807471894551
            client-secret: 3bc2f2ad60673e6a19cf87d442651663
            scope:
            - email
            - public_profile
            
          naver:
            client-id: WKxvwO_cmlFlcBNzQXlS
            client-secret: N_UQ4QbYjK
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.     
                

